/**
 * Represents a product item in the E-Store catalog
 * @interface Product
 */
export interface Product {
  /** Unique product identifier */
  id: number;
  /** Product display name */
  title: string;
  /** Product price in USD */
  price: number;
  /** Detailed product description */
  description: string;
  /** Product category (e.g., 'electronics', 'clothing') */
  category: string;
  /** URL to product image */
  image: string;
  /** Optional product rating information */
  rating?: {
    /** Average rating score (0-5) */
    rate: number;
    /** Number of ratings received */
    count: number;
  };
}

/**
 * Represents filter and sorting state for product display
 * @interface FilterState
 */
export interface FilterState {
  /** Search query term */
  searchTerm: string;
  /** Selected category filter (null = show all) */
  selectedCategory: string | null;
  /** Price sort order: 'asc' (low to high), 'desc' (high to low), 'none' (no sort) */
  sortBy: 'asc' | 'desc' | 'none';
}

/**
 * Represents the complete products data state
 * @interface ProductsState
 */
export interface ProductsState {
  /** Array of all loaded products */
  products: Product[];
  /** Loading indicator while fetching data */
  loading: boolean;
  /** Error message if data fetch fails */
  error: string | null;
  /** List of available product categories */
  categories: string[];
}

/**
 * AI-enhanced product description response
 * Contains description, suggestions, and summary generated by the AI service
 * @interface AIDescriptionResponse
 */
export interface AIDescriptionResponse {
  /** Enhanced product description generated by AI */
  description: string;
  /** Array of shopping suggestion recommendations */
  suggestions: string[];
  /** Brief summary of the product */
  summary: string;
}
